VERZIJA=CDX
MODUL=sc1g_ut


SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\ut\\1g\\


PRGS=num_ut.prg str_ut.prg time_ut.prg ut.prg arr_ut.prg log.prg com_ut.prg test_str.prg
CS=
ASMS=

include  $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

