VERZIJA=CDX
MODUL=sc1g_os

SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\os\\1g\\

PRGS=os_ut.prg file_io.prg
CS=

ASMS=mkdir.asm rmdir.asm setdate.asm settime.asm

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
