VERZIJA=CDX
MODUL=sc1g_sql

SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\sql\\1g\\

PRGS=sql.prg sql_db.prg sql_ut.prg sql_ext.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
