VERZIJA=CDX
MODUL=sc1g_ba


SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\base\\1g\\

PRGS=base.prg err.prg gvars.prg gw.prg
ASMS=
CS=arg0.c

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

