VERZIJA=CDX
MODUL=sc1g_pr

PRGS=print.prg ptxt.prg
CS=
ASMS=isprint.asm lptswap.asm



SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\print\\1g\\


include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
