VERZIJA=CDX
MODUL=sc1g_db


SRCDOSROOT=c:\\dev\\af\\cl-sclib\\sclib\\db\\1g\\

PRGS=db.prg db_adm.prg db_cre.prg db_sez.prg qry_lang.prg kompat.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
